[package]
name = "workflows-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
js-sys = "0.3.85"
serde = "1.0.228"
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.108"
wasm-bindgen-futures = "0.4.58"
worker = "0.7.4"
